package ui;

import Torres.Util;
import beu.Curso;
import beu.Estudiante;
import bll.GestionEstudiante;
import java.io.IOException;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class frmRegistroEstudiantes extends javax.swing.JInternalFrame {

    private final String titulo = "\n";
    private GestionEstudiante estudiantesbll = new GestionEstudiante();

    /**
     * Creates new form frmRegistroEstudiantes
     */
    public frmRegistroEstudiantes() {
        initComponents();
        try {
            iniciarListado();

        } catch (Exception e) {
            Util.imprimir(e.toString());
            verMensaje("Error al guardar al estudiante", titulo, JOptionPane.ERROR_MESSAGE);
        }

    }

    private static void verMensaje(String mensaje, String titulo, int tipo) {
        JOptionPane.showMessageDialog(null, mensaje, titulo, tipo);
    }

    private void iniciarListado() throws IOException {
        estudiantesbll.getEstudiantes();
    }

    private String verificarClub(JCheckBox chk) {
        return chk.isSelected() ? chk.getText() : "";

    }

    private void crearEstudiante() {
        Estudiante nuevo = new Estudiante();
        nuevo.setCedula(this.txtCedula.getText());
        nuevo.setNombre(this.txtNombre.getText());
        nuevo.setApellido(this.txtApellido.getText());
        nuevo.setCarrera(this.cbxCarrera.getSelectedItem().toString());
        nuevo.addClub(this.verificarClub(chkdanza));
        nuevo.addClub(this.verificarClub(this.chkandinismo));
        nuevo.addClub(this.verificarClub(this.chkelectronica));
        nuevo.addClub(this.verificarClub(this.chkrobotica));
        nuevo.addClub(this.verificarClub(this.chkscout));
        nuevo.addClub(this.verificarClub(this.chksoftware));
        estudiantesbll.getEstudiantes().add(nuevo);
    }

    private void archivar() throws IOException {
        estudiantesbll.archivar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosPersonales = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        pnlDatosAcademicos = new javax.swing.JPanel();
        lblCarrera = new javax.swing.JLabel();
        cbxCarrera = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        chkdanza = new javax.swing.JCheckBox();
        chkandinismo = new javax.swing.JCheckBox();
        chksoftware = new javax.swing.JCheckBox();
        chkelectronica = new javax.swing.JCheckBox();
        chkscout = new javax.swing.JCheckBox();
        chkrobotica = new javax.swing.JCheckBox();
        btnGuardarRegistroestudiante = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro de estudiantes");

        pnlDatosPersonales.setBackground(new java.awt.Color(204, 255, 255));
        pnlDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Serif", 1, 24))); // NOI18N

        lbl.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        lbl.setText("Cedula:");

        lbl1.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        lbl1.setText("Apellido");

        lbl2.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        lbl2.setText("Nombres:");

        javax.swing.GroupLayout pnlDatosPersonalesLayout = new javax.swing.GroupLayout(pnlDatosPersonales);
        pnlDatosPersonales.setLayout(pnlDatosPersonalesLayout);
        pnlDatosPersonalesLayout.setHorizontalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1)
                            .addComponent(lbl))
                        .addGap(32, 32, 32))
                    .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addGap(23, 23, 23)))
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellido)
                    .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosPersonalesLayout.setVerticalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnlDatosAcademicos.setBackground(new java.awt.Color(204, 204, 255));
        pnlDatosAcademicos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Academicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Serif", 1, 24))); // NOI18N

        lblCarrera.setText("Carrera");

        cbxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria en Software", "Ingenieria en sistemas", "Ingenieria Computacion", "Ingenieria Mecatronica" }));
        cbxCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosAcademicosLayout = new javax.swing.GroupLayout(pnlDatosAcademicos);
        pnlDatosAcademicos.setLayout(pnlDatosAcademicosLayout);
        pnlDatosAcademicosLayout.setHorizontalGroup(
            pnlDatosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosAcademicosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblCarrera)
                .addGap(106, 106, 106)
                .addComponent(cbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        pnlDatosAcademicosLayout.setVerticalGroup(
            pnlDatosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosAcademicosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(pnlDatosAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarrera))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos extracurriculares"));

        chkdanza.setText("Club de Danza");

        chkandinismo.setText("Club de andinismo");

        chksoftware.setText("Club de Software");

        chkelectronica.setText("Club de electronica");

        chkscout.setText("Club Scout");

        chkrobotica.setText("Club Robotica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkelectronica)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkdanza)
                            .addComponent(chkandinismo))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chksoftware)
                            .addComponent(chkscout)
                            .addComponent(chkrobotica))))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkdanza)
                    .addComponent(chkrobotica))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chksoftware)
                    .addComponent(chkandinismo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkelectronica)
                    .addComponent(chkscout))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnGuardarRegistroestudiante.setBackground(new java.awt.Color(0, 204, 204));
        btnGuardarRegistroestudiante.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        btnGuardarRegistroestudiante.setText("Guardar");
        btnGuardarRegistroestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRegistroestudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardarRegistroestudiante)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlDatosAcademicos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDatosAcademicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnGuardarRegistroestudiante)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarRegistroestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegistroestudianteActionPerformed
        // TODO add your handling code here:
        try {
            crearEstudiante();
            archivar();
            verMensaje("Exito al guardar al estudiante", titulo, JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            Util.imprimir("error:" + e.toString());
            verMensaje("Error al guardar al estudiante", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarRegistroestudianteActionPerformed

    private void cbxCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCarreraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarRegistroestudiante;
    private javax.swing.JComboBox<String> cbxCarrera;
    private javax.swing.JCheckBox chkandinismo;
    private javax.swing.JCheckBox chkdanza;
    private javax.swing.JCheckBox chkelectronica;
    private javax.swing.JCheckBox chkrobotica;
    private javax.swing.JCheckBox chkscout;
    private javax.swing.JCheckBox chksoftware;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JPanel pnlDatosAcademicos;
    private javax.swing.JPanel pnlDatosPersonales;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
