package ui;

import Torres.Util;
import bll.GestionMatricula;
import java.io.IOException;
import javax.swing.JOptionPane;

public class frmRegistroDeCalificaciones extends javax.swing.JInternalFrame {

    private GestionMatricula matriculabll = new GestionMatricula();
    private final String titulo = "Registro de Calificaciones\n";

    private boolean validar (){
        float nota = (float )this.spnValorCalificacion.getValue();
        if(nota== 0.f){
            verMensaje("Calificacion no valida",JOptionPane.INFORMATION_MESSAGE);
        }
        return true;
    }
    
    
    public void consultarMatricula() throws IOException {
        String numero = this.txtNumeroMatricula.getText();
        matriculabll.consultar(numero);
        this.txtDatosMatricula.setText(matriculabll.imprimir());
    }

    public frmRegistroDeCalificaciones() {
        initComponents();
    }

    private void verMensaje(String mensaje, int tipo) {
        JOptionPane.showMessageDialog(null, mensaje, titulo, tipo);
    }

    private String calificar() throws IOException {
        float notas = (float) this.spnValorCalificacion.getValue();
        String mensaje = this.matriculabll.calificar(notas);
        matriculabll.archivar();
        return mensaje;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroCalificaciones = new javax.swing.JPanel();
        lblRegistroCalificaciones = new javax.swing.JLabel();
        lblNumeroMatricula = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatosMatricula = new javax.swing.JTextArea();
        btnBuscarNMatricula = new javax.swing.JButton();
        pnlCalificacion = new javax.swing.JPanel();
        lblValorCalificacion = new javax.swing.JLabel();
        spnValorCalificacion = new javax.swing.JSpinner();
        txtNumeroMatricula = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlRegistroCalificaciones.setBackground(new java.awt.Color(204, 255, 255));

        lblRegistroCalificaciones.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        lblRegistroCalificaciones.setText("Registro de Calificaciones");

        lblNumeroMatricula.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        lblNumeroMatricula.setText("N° Matricula:");

        txtDatosMatricula.setBackground(new java.awt.Color(0, 204, 204));
        txtDatosMatricula.setColumns(20);
        txtDatosMatricula.setRows(5);
        txtDatosMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Matricula Registrada"));
        jScrollPane1.setViewportView(txtDatosMatricula);

        btnBuscarNMatricula.setIcon(new javax.swing.ImageIcon("/home/labctr/Descargas/xmag_search_find_export_locate_5984.png")); // NOI18N
        btnBuscarNMatricula.setMnemonic('B');
        btnBuscarNMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNMatriculaActionPerformed(evt);
            }
        });

        pnlCalificacion.setBackground(new java.awt.Color(0, 204, 204));
        pnlCalificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Calificacion"));

        lblValorCalificacion.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        lblValorCalificacion.setText("Valor");

        spnValorCalificacion.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(20.0f), Float.valueOf(0.01f)));

        javax.swing.GroupLayout pnlCalificacionLayout = new javax.swing.GroupLayout(pnlCalificacion);
        pnlCalificacion.setLayout(pnlCalificacionLayout);
        pnlCalificacionLayout.setHorizontalGroup(
            pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalificacionLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblValorCalificacion)
                .addGap(69, 69, 69)
                .addComponent(spnValorCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        pnlCalificacionLayout.setVerticalGroup(
            pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalificacionLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorCalificacion)
                    .addComponent(spnValorCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(0, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroCalificacionesLayout = new javax.swing.GroupLayout(pnlRegistroCalificaciones);
        pnlRegistroCalificaciones.setLayout(pnlRegistroCalificacionesLayout);
        pnlRegistroCalificacionesLayout.setHorizontalGroup(
            pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroCalificacionesLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegistroCalificacionesLayout.createSequentialGroup()
                        .addComponent(lblNumeroMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRegistroCalificaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarNMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroCalificacionesLayout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addGroup(pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar)
                    .addGroup(pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlCalificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );
        pnlRegistroCalificacionesLayout.setVerticalGroup(
            pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroCalificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistroCalificaciones)
                .addGroup(pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroCalificacionesLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlRegistroCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumeroMatricula)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroCalificacionesLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnBuscarNMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistroCalificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistroCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            String mensaje = this.calificar();
            verMensaje("Guardado", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            Util.imprimir("Error" + e.toString());
            verMensaje("Error al buscar la matricula", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarNMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNMatriculaActionPerformed
        // TODO add your handling code here:
        try {
            consultarMatricula();
        } catch (Exception e) {
            Util.imprimir("Error" + e.toString());
            verMensaje("Error al buscar la matricula", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarNMatriculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarNMatricula;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumeroMatricula;
    private javax.swing.JLabel lblRegistroCalificaciones;
    private javax.swing.JLabel lblValorCalificacion;
    private javax.swing.JPanel pnlCalificacion;
    private javax.swing.JPanel pnlRegistroCalificaciones;
    private javax.swing.JSpinner spnValorCalificacion;
    private javax.swing.JTextArea txtDatosMatricula;
    private javax.swing.JTextField txtNumeroMatricula;
    // End of variables declaration//GEN-END:variables
}
