package ui;

import Torres.Util;
import beu.Curso;
import beu.Estudiante;
import bll.GestionCurso;
import bll.GestionEstudiante;
import bll.GestionMatricula;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

public class frmRegistroDeMatricula extends javax.swing.JInternalFrame {

    private final String titulo = "\n";
    //Servicio, bll 
    private GestionCurso cursosbll = new GestionCurso();
    private GestionEstudiante estudiantesbll = new GestionEstudiante();
    private GestionMatricula matriculabll = new GestionMatricula();
    private List<Estudiante> estudiantes;
    private List<Curso> cursos;
//validar antes de crear

    private boolean validar() {
        Curso cr = (Curso) this.cmbCursos.getSelectedItem();
        Estudiante es = (Estudiante) this.cmbEstudiantes.getSelectedItem();
        if (cr.getTitulo().equals("** Seleccione **")) {
            verMensaje("Error al crear la matricula", titulo, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (es.getCedula() == null) {
            verMensaje("Error al crear el estudiante", titulo, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void crearMatricula() throws IOException {
        //se transforma en estudiantes y se guarda en la variable 

        Curso cr = (Curso) this.cmbCursos.getSelectedItem();
        Estudiante es = (Estudiante) this.cmbEstudiantes.getSelectedItem();
        matriculabll.crear();
        matriculabll.configurar(cr, es);
        matriculabll.archivar();

    }

    private void leerEstudiantes() {
        try {
            Estudiante ficticio = new Estudiante();
            ficticio.setNombre("** Eliga uno **");
            ficticio.setApellido("");
            this.cmbEstudiantes.addItem(ficticio);
            estudiantes = estudiantesbll.leerEstudiantes();
            for (Estudiante est : estudiantes) {
                this.cmbEstudiantes.addItem(est);
            }
        } catch (Exception e) {
            Util.imprimir("error:" + e.toString());
            verMensaje("Error al leer los cursos ", titulo, JOptionPane.ERROR_MESSAGE);
        }

    }

    private void leerCursos() {
        try {
            Curso ficticio = new Curso("** Seleccione ** ", "", 0f);
            this.cmbCursos.addItem(ficticio);

            cursos = cursosbll.getCursos();
            for (Curso c : cursos) {
                this.cmbCursos.addItem(c);
            }

        } catch (Exception e) {
            Util.imprimir("error:" + e.toString());
            verMensaje("Error al leer los cursos ", titulo, JOptionPane.ERROR_MESSAGE);
        }

    }

    private static void verMensaje(String mensaje, String titulo, int tipo) {
        JOptionPane.showMessageDialog(null, mensaje, titulo, tipo);
    }

    public frmRegistroDeMatricula() throws IOException {
        initComponents();
        leerCursos();
        leerEstudiantes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroMatricula = new javax.swing.JPanel();
        lblEstudiante = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        cmbEstudiantes = new javax.swing.JComboBox<>();
        cmbCursos = new javax.swing.JComboBox<>();
        btnGUardarRefistroMatricula = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlRegistroMatricula.setBackground(new java.awt.Color(102, 255, 204));
        pnlRegistroMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro De Matricula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Serif", 1, 18))); // NOI18N

        lblEstudiante.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        lblEstudiante.setText("Estudiante:");

        lblCurso.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        lblCurso.setText("Curso:");

        cmbEstudiantes.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N

        cmbCursos.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N

        btnGUardarRefistroMatricula.setBackground(new java.awt.Color(0, 204, 204));
        btnGUardarRefistroMatricula.setFont(new java.awt.Font("Liberation Serif", 0, 18)); // NOI18N
        btnGUardarRefistroMatricula.setText("Guardar");
        btnGUardarRefistroMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGUardarRefistroMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroMatriculaLayout = new javax.swing.GroupLayout(pnlRegistroMatricula);
        pnlRegistroMatricula.setLayout(pnlRegistroMatriculaLayout);
        pnlRegistroMatriculaLayout.setHorizontalGroup(
            pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroMatriculaLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGUardarRefistroMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegistroMatriculaLayout.createSequentialGroup()
                        .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEstudiante)
                            .addComponent(lblCurso))
                        .addGap(39, 39, 39)
                        .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstudiantes, 0, 318, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );
        pnlRegistroMatriculaLayout.setVerticalGroup(
            pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroMatriculaLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudiante)
                    .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlRegistroMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurso))
                .addGap(74, 74, 74)
                .addComponent(btnGUardarRefistroMatricula)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(pnlRegistroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistroMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGUardarRefistroMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUardarRefistroMatriculaActionPerformed
        // TODO add your handling code here:
        try {
            if (validar()) {
                crearMatricula();
                verMensaje(" Matricula creada!", titulo, JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            Util.imprimir("error:" + e.toString());
            verMensaje("Error al crear la matricula", titulo, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGUardarRefistroMatriculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGUardarRefistroMatricula;
    private javax.swing.JComboBox<Curso> cmbCursos;
    private javax.swing.JComboBox<Estudiante> cmbEstudiantes;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JPanel pnlRegistroMatricula;
    // End of variables declaration//GEN-END:variables
}
